### ISSUE TITLE
upload resources file as for example

### ISSUE THREAD

**Issue by coolzoom** [ChrisJanusiewicz/simple-graphics-engine#1]
Hi Chris,
Could you please upload some resource file inside the Media folder
Including Models/Worlds/Textures

Thanks and best regards

**Comment by flexjdev** [comment]
Hi Coolzoom,

I found some resources which I uploaded to the project repo

Best,

Chris

**Comment by coolzoom** [comment]
Hi Chris,
Thanks! it's working!

best regards
